// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI-only (migrate, db push, introspect). Points at Supabase's direct,
    // non-pooled connection since these commands run DDL and don't play
    // well through the pgbouncer pooler. The running app uses a separate
    // pooled connection — see src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
